name: Build Reusable Workflow

on:
  workflow_call:
    inputs:
      language:
        description: 'Programming language for the build'
        required: true
        type: string
      environment:
        description: 'Deployment environment'
        required: true
        type: string
      dotnet-version:
        description: 'The .NET version to use'
        required: true
        type: string
    #secrets:
      # Se precisar de tokens para autenticação em outros serviços, adicione-os aqui
      # SONAR_TOKEN:
      #   required: true

jobs:
  build:
    runs-on: windows-latest  # Ambiente Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore dependencies
        run: |
          cd aspnet-pipelines
          dotnet restore

      - name: Build project
        run: |
          cd aspnet-pipelines
          dotnet build --configuration Release

      - name: Run unit tests
        run: |
          cd aspnet-pipelines
          dotnet test --configuration Release

      - name: Publish project
        run: |
          cd aspnet-pipelines
          dotnet publish --configuration Release --output ./publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: aspnet-build
          path: aspnet-pipelines/bin/Release/net7.0/publish
